// Package models holds the registry of NVIDIA build.nvidia.com playground
// models and their reverse-engineered NVCF invocation parameters.
//
// The build.nvidia.com playground calls
//
//	POST https://buildapi.ngc.nvidia.com/v2/predict/models/{namespace}/{slug}
//	              nv-function-id: {functionID}
//	              nv-captcha-token: <hCaptcha token>
//
// Each playground model has its own {slug} and nv-function-id. The
// {namespace} is currently shared across all playground models
// (qc69jvmznzxy). The map below is generated by
// scripts/scrape_playground_models.py: it fetches the SSR-rendered model
// list from https://build.nvidia.com/models, extracts every endpooint
// resource id, then probes each playground page for the server-rendered
// "nvcfFunctionId" + "namespace". Models whose playground page does not
// inline a function id are skipped (image/tts/video models, or chat models
// that resolve their function id at runtime — SKIPPED until runtime capture
// is implemented).
//
// To regenerate the data, run
//
//	python3 scripts/scrape_playground_models.py > scripts/playground_models.json
//
// then refresh the Models map (the slug/namespace/functionID triple per id).
package models

import (
	"fmt"
	"sync"
)

// Namespace is the NVCF namespace embedded in every playground predict URL.
// All known sandbox models currently share this one namespace.
const Namespace = "qc69jvmznzxy"

// PredictBase is the anonymous predict gateway host used since 2026-08.
// (The legacy api.ngc.nvidia.com host now returns 404 for anonymous
// accounts.)
const PredictBase = "https://buildapi.ngc.nvidia.com"

// ModelInfo is the per-model NVCF invocation data needed to call the
// (anonymous, hCaptcha-gated) playground predict endpoint.
type ModelInfo struct {
	// Slug is the model name segment used in the predict URL path
	// (everything after the last "/"). E.g. "kimi-k3" for
	// "moonshotai/kimi-k3".
	Slug string
	// Namespace is the NVCF namespace for this model. Currently always
	// Namespace, but kept per-model in case NVIDIA splits sandboxes.
	Namespace string
	// FunctionID is the nv-function-id header value (per-model UUID).
	FunctionID string
	Capability *ModelCapability
}

type ModelCapability struct {
	ToolCalling      bool
	StructuredOutput bool
	Vision           bool
	// Thinking means the model accepts chat_template_kwargs with
	// enable_thinking. Leave false unless a live probe verified it: most of
	// the 2026-08 catalog (e.g. kimi-k3) rejects thinking kwargs with 400.
	Thinking bool
}

// PredictEndpoint returns the predict URL for a model info.
func (m ModelInfo) PredictEndpoint() string {
	return PredictBase + "/v2/predict/models/" + m.Namespace + "/" + m.Slug
}

// DefaultModel is the project's default playground model.
//
// The historical default z-ai/glm-5.2 was removed from the anonymous
// catalog in 2026-08 (playground SSR still inlines a function id, but the
// backend returns 404 via grpc.nvcf.nvidia.com); moonshotai/kimi-k3 is a
// verified-working replacement.
const DefaultModel = "moonshotai/kimi-k3"

// Models is the registry of all supported build.nvidia.com playground models.
// Generated from scripts/playground_models.json via scripts/scrape_playground_models.py.
//
// Source: https://build.nvidia.com/models (2026-08-30; 24 endpoints, 11 with
// inline nvcfFunctionId).
//
// Function ids are almost always unique per model, but NVIDIA aliases some
// backend versions to one NVCF function — e.g. nvidia/ising-calibration-1-35b-a3b
// and nvidia/ising-calibration-1.5-31b share 499210d3. That is fine: the
// predict endpoint is keyed by namespace/slug, which IS unique per registry key.
var Models = map[string]ModelInfo{
	"deepseek-ai/deepseek-v4-flash-0731":            {Slug: "deepseek-v4-flash-0731", Namespace: Namespace, FunctionID: "281478d0-f307-49f4-9e0f-080b63b16c47"},
	"deepseek-ai/deepseek-v4-pro-0813":              {Slug: "deepseek-v4-pro-0813", Namespace: Namespace, FunctionID: "6e70713f-4eeb-4ef7-b4f8-2d984f4141f6"},
	"google/diffusiongemma-26b-a4b-it":              {Slug: "diffusiongemma-26b-a4b-it", Namespace: Namespace, FunctionID: "ffd13b18-1c55-4a7a-b71a-acbfde9ce8a0"},
	"meta/muse-glimmer-30b":                         {Slug: "muse-glimmer-30b", Namespace: Namespace, FunctionID: "fd21cc19-b4ff-4949-ba07-90dd663c416a"},
	"minimaxai/minimax-m3":                          {Slug: "minimax-m3", Namespace: Namespace, FunctionID: "87ea0ddc-cff1-4bca-bf8b-3bd98a35ddd0"},
	"moonshotai/kimi-k3":                            {Slug: "kimi-k3", Namespace: Namespace, FunctionID: "1586112a-925c-48af-8631-7c815dbd749c"},
	"nvidia/ising-calibration-1.5-31b":              {Slug: "ising-calibration-1.5-31b", Namespace: Namespace, FunctionID: "499210d3-3bf7-44bf-88b5-9460edfa8a38"},
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": {Slug: "nemotron-3-nano-omni-30b-a3b-reasoning", Namespace: Namespace, FunctionID: "c4ed50ff-b5c3-409d-ab57-b79c33f5bb39"},
	"nvidia/nemotron-3-ultra-550b-a55b":             {Slug: "nemotron-3-ultra-550b-a55b", Namespace: Namespace, FunctionID: "948fe171-ce7a-4332-8bc0-5e14e90259f9"},
	"nvidia/nemotron-3.5-lightning-30b-a3b":         {Slug: "nemotron-3.5-lightning-30b-a3b", Namespace: Namespace, FunctionID: "0a213807-640b-43fb-bfbf-2919f9b666ad"},
	"poolside/laguna-xs-2.1":                        {Slug: "laguna-xs-2.1", Namespace: Namespace, FunctionID: "4a8f921c-c99d-4cde-92c1-c92ba9e4c50f"},
}

// registryMu guards Models against concurrent Refresh swaps. Lookup reads the
// map under RLock so a live Refresh never tears a half-replaced map.
var registryMu sync.RWMutex

// All returns a snapshot of the current registry (map copy).
func All() map[string]ModelInfo {
	registryMu.RLock()
	defer registryMu.RUnlock()
	out := make(map[string]ModelInfo, len(Models))
	for k, v := range Models {
		out[k] = v
	}
	return out
}

// Replace atomically swaps the whole registry (used by Refresh for live
// catalog updates).
func Replace(m map[string]ModelInfo) {
	registryMu.Lock()
	defer registryMu.Unlock()
	Models = m
}

// Lookup returns the ModelInfo for a model id ("publisher/slug").
// The empty string resolves to DefaultModel.
// Lookup returns the ModelInfo for a model id ("publisher/slug").
// The empty string resolves to DefaultModel.
func Lookup(model string) (ModelInfo, error) {
	if model == "" {
		model = DefaultModel
	}
	registryMu.RLock()
	info, ok := Models[model]
	registryMu.RUnlock()
	if !ok {
		return ModelInfo{}, &ErrUnknownModel{Model: model}
	}
	return info, nil
}

// ErrUnknownModel is returned by Lookup for unknown model ids.
type ErrUnknownModel struct {
	Model string
}

func (e *ErrUnknownModel) Error() string {
	return fmt.Sprintf("unknown model: %s", e.Model)
}
